---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnrm-headless-svc-operator
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: '9115'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUG
              value: 'false'
          image: pmialon/cnrm-headless-svc-operator:0.2.2
          imagePullPolicy: Always
          name: shell-operator
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 128Mi
          securityContext:
            runAsUser: 10297
            runAsGroup: 10297
      serviceAccountName: cnrm-headless-svc-operator
