apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: cnrm-headless-svc-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnrm-headless-svc-operator
    app.kubernetes.io/part-of: cnrm-headless-svc
    app.kubernetes.io/version: v0.1.0
  name: cnrm-headless-svc-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: cnrm-headless-svc-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnrm-headless-svc-operator
    app.kubernetes.io/part-of: cnrm-headless-svc
    app.kubernetes.io/version: v0.1.0
  name: service-edit
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: cnrm-headless-svc-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnrm-headless-svc-operator
    app.kubernetes.io/part-of: cnrm-headless-svc
    app.kubernetes.io/version: v0.1.0
  name: cnrm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnrm-viewer
subjects:
- kind: ServiceAccount
  name: cnrm-headless-svc-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: cnrm-headless-svc-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnrm-headless-svc-operator
    app.kubernetes.io/part-of: cnrm-headless-svc
    app.kubernetes.io/version: v0.1.0
  name: service-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-edit
subjects:
- kind: ServiceAccount
  name: cnrm-headless-svc-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: cnrm-headless-svc-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnrm-headless-svc-operator
    app.kubernetes.io/part-of: cnrm-headless-svc
    app.kubernetes.io/version: v0.1.0
  name: cnrm-headless-svc-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: cnrm-headless-svc-operator
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: cnrm-headless-svc-operator
      app.kubernetes.io/part-of: cnrm-headless-svc
      app.kubernetes.io/version: v0.1.0
  template:
    metadata:
      annotations:
        prometheus.io/port: "9115"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: cnrm-headless-svc-operator
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: cnrm-headless-svc-operator
        app.kubernetes.io/part-of: cnrm-headless-svc
        app.kubernetes.io/version: v0.1.0
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEBUG
          value: "false"
        image: pmialon/cnrm-headless-svc-operator:0.2.0
        imagePullPolicy: Always
        name: shell-operator
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsGroup: 10297
          runAsUser: 10297
      serviceAccountName: cnrm-headless-svc-operator
