---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/instance: cnrm-headless-svc-operator
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: cnrm-headless-svc-operator
  app.kubernetes.io/part-of: cnrm-headless-svc
  app.kubernetes.io/version: v0.2.2
resources:
  - cnrm-headless-svc-operator-deploy.yaml
  - cnrm-headless-svc-operator-sa.yaml
  - cnrm-rolebinding.yaml
  - service-edit-role.yaml
  - service-edit-rolebinding.yaml
