apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-edit
subjects:
- kind: ServiceAccount
  name: cnrm-headless-svc-operator
